---
title: "Stardew Valley: Farm Planning"
author: "Nick D. Ungson"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '2'
---

**Last updated:** `r Sys.time()`

# Prep

```{r eval = TRUE, echo = TRUE, message = FALSE, results = 'hide', warning = FALSE}
require(tidyverse)
require(here)

crops <- read.csv(
  here("crops.csv"), 
  header = TRUE, 
  stringsAsFactors = TRUE)

colnames(crops)
```

# Spring

What are the most profitable (by *gold per day*) spring crops?

```{r}
crops %>%
  filter(season == "spring", 
         crop_type == "fruit" | 
           crop_type == "vegetable") %>% 
  select(name = crop_name, 
         type = crop_type, 
         price = seed_price, 
         gpd = gold_day, 
         notes1:notes2) %>% 
  arrange(desc(gpd))
```

**Going to try and plant the following in 2nd Spring:**

* 32 cauliflower
* 16 kale
* 16 potato
* 16 garlic
* 16 parsnip
* 32 green beans

* 8 blue jazz
* 8 tulip

**how much will it cost?**

```{r}
PriceSeeds <- function(crop, n){
  price <- crops[crops$crop_name == crop, "seed_price"]
  
  return(price * n)
}
```

On **Spring 1**, you need:
```{r}
PriceSeeds("cauliflower", 32) + 
  PriceSeeds("green bean", 32) + 
  PriceSeeds("kale", 16) + 
  PriceSeeds("potato", 16) + 
  PriceSeeds("garlic", 16) + 
  PriceSeeds("parsnip", 16) + 
  PriceSeeds("blue jazz", 8) + 
  PriceSeeds("tulip", 8)
```


